version: '3.8'

services:
    postgres_integra:
        image: postgres:16
        container_name: pgsql_integra
        restart: always
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: integra
        ports:
            - '5432:5432'
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - integra_network

    redis_integra:
        image: redis:latest
        container_name: redis_integra
        restart: always
        ports:
            - '6379:6379'
        volumes:
            - redisdata:/data
        networks:
            - integra_network

    minio_integra:
        image: minio/minio:latest
        container_name: minio_integra
        restart: always
        environment:
            MINIO_ROOT_USER: admin
            MINIO_ROOT_PASSWORD: admin123
        ports:
            - '9000:9000'
            - '9001:9001'
        volumes:
            - miniodata:/data
        command: server /data --console-address ":9001"
        networks:
            - integra_network

volumes:
    pgdata:
    redisdata:
    miniodata:

networks:
    integra_network:
        name: integra_network
        driver: bridge
        external: true
